import { Customer, Order, Case, Escalation } from '../types';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-1001',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    phone: '+91 98201 44521',
    tier: 'platinum',
    riskScore: 8,
    trustScore: 94,
    totalOrders: 38,
    totalSpent: 84950,
    lifetimeRefunds: 1,
    status: 'active',
    createdAt: '2023-04-12T10:00:00Z',
  },
  {
    id: 'CUST-1002',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    phone: '+91 99341 88912',
    tier: 'gold',
    riskScore: 12,
    trustScore: 88,
    totalOrders: 21,
    totalSpent: 42100,
    lifetimeRefunds: 0,
    status: 'active',
    createdAt: '2023-08-19T14:20:00Z',
  },
  {
    id: 'CUST-1003',
    name: 'Vikram Singhania',
    email: 'vikram.singh@example.com',
    phone: '+91 97112 55309',
    tier: 'standard',
    riskScore: 82,
    trustScore: 31,
    totalOrders: 2,
    totalSpent: 52000,
    lifetimeRefunds: 2,
    status: 'flagged',
    createdAt: '2024-01-05T09:15:00Z',
  },
  {
    id: 'CUST-1004',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@example.com',
    phone: '+91 98450 12903',
    tier: 'enterprise',
    riskScore: 5,
    trustScore: 98,
    totalOrders: 114,
    totalSpent: 345000,
    lifetimeRefunds: 3,
    status: 'active',
    createdAt: '2022-11-01T08:00:00Z',
  },
  {
    id: 'CUST-1005',
    name: 'Rohan Mehra',
    email: 'rohan.m@example.com',
    phone: '+91 91672 90114',
    tier: 'gold',
    riskScore: 18,
    trustScore: 82,
    totalOrders: 15,
    totalSpent: 29400,
    lifetimeRefunds: 1,
    status: 'active',
    createdAt: '2023-06-11T12:00:00Z',
  },
  {
    id: 'CUST-1006',
    name: 'Sneha Verma',
    email: 'sneha.v@example.com',
    phone: '+91 98114 67022',
    tier: 'platinum',
    riskScore: 9,
    trustScore: 91,
    totalOrders: 42,
    totalSpent: 96000,
    lifetimeRefunds: 0,
    status: 'active',
    createdAt: '2023-02-14T11:30:00Z',
  },
  {
    id: 'CUST-1007',
    name: 'Karan Kapoor',
    email: 'karan.k@example.com',
    phone: '+91 99203 11849',
    tier: 'standard',
    riskScore: 45,
    trustScore: 62,
    totalOrders: 6,
    totalSpent: 14200,
    lifetimeRefunds: 1,
    status: 'active',
    createdAt: '2023-10-09T16:45:00Z',
  },
  {
    id: 'CUST-1008',
    name: 'Neha Roy',
    email: 'neha.roy@example.com',
    phone: '+91 98301 77215',
    tier: 'gold',
    riskScore: 14,
    trustScore: 86,
    totalOrders: 19,
    totalSpent: 38700,
    lifetimeRefunds: 0,
    status: 'active',
    createdAt: '2023-05-22T09:40:00Z',
  },
  {
    id: 'CUST-1009',
    name: 'Aditya Kulkarni',
    email: 'aditya.k@example.com',
    phone: '+91 94220 88319',
    tier: 'standard',
    riskScore: 28,
    trustScore: 74,
    totalOrders: 9,
    totalSpent: 18500,
    lifetimeRefunds: 0,
    status: 'active',
    createdAt: '2023-09-15T15:10:00Z',
  },
  {
    id: 'CUST-1010',
    name: 'Meera Nambiar',
    email: 'meera.n@example.com',
    phone: '+91 97441 55602',
    tier: 'platinum',
    riskScore: 6,
    trustScore: 95,
    totalOrders: 51,
    totalSpent: 128000,
    lifetimeRefunds: 1,
    status: 'active',
    createdAt: '2022-09-30T10:15:00Z',
  },
  {
    id: 'CUST-1011',
    name: 'Deepak Joshi',
    email: 'deepak.j@example.com',
    phone: '+91 98230 44911',
    tier: 'standard',
    riskScore: 75,
    trustScore: 40,
    totalOrders: 4,
    totalSpent: 48000,
    lifetimeRefunds: 2,
    status: 'flagged',
    createdAt: '2024-02-01T13:20:00Z',
  },
  {
    id: 'CUST-1012',
    name: 'Kavita Sundaram',
    email: 'kavita.s@example.com',
    phone: '+91 98402 33190',
    tier: 'gold',
    riskScore: 11,
    trustScore: 89,
    totalOrders: 27,
    totalSpent: 64200,
    lifetimeRefunds: 0,
    status: 'active',
    createdAt: '2023-03-18T14:50:00Z',
  },
  {
    id: 'CUST-1013',
    name: 'Tanmay Ghosh',
    email: 'tanmay.g@example.com',
    phone: '+91 98311 90234',
    tier: 'standard',
    riskScore: 22,
    trustScore: 78,
    totalOrders: 11,
    totalSpent: 22100,
    lifetimeRefunds: 0,
    status: 'active',
    createdAt: '2023-07-29T11:05:00Z',
  },
  {
    id: 'CUST-1014',
    name: 'Ritu Choudhury',
    email: 'ritu.c@example.com',
    phone: '+91 98105 88129',
    tier: 'gold',
    riskScore: 15,
    trustScore: 85,
    totalOrders: 24,
    totalSpent: 51900,
    lifetimeRefunds: 1,
    status: 'active',
    createdAt: '2023-04-03T16:00:00Z',
  },
  {
    id: 'CUST-1015',
    name: 'Arjun Bansal',
    email: 'arjun.b@example.com',
    phone: '+91 98710 44299',
    tier: 'enterprise',
    riskScore: 4,
    trustScore: 97,
    totalOrders: 89,
    totalSpent: 284000,
    lifetimeRefunds: 2,
    status: 'active',
    createdAt: '2022-12-10T09:30:00Z',
  },
  {
    id: 'CUST-1016',
    name: 'Pooja Hegde',
    email: 'pooja.h@example.com',
    phone: '+91 99801 22345',
    tier: 'standard',
    riskScore: 33,
    trustScore: 71,
    totalOrders: 8,
    totalSpent: 16800,
    lifetimeRefunds: 0,
    status: 'active',
    createdAt: '2023-11-20T17:15:00Z',
  },
  {
    id: 'CUST-1017',
    name: 'Manish Tiwari',
    email: 'manish.t@example.com',
    phone: '+91 94150 99881',
    tier: 'gold',
    riskScore: 19,
    trustScore: 81,
    totalOrders: 16,
    totalSpent: 31500,
    lifetimeRefunds: 1,
    status: 'active',
    createdAt: '2023-08-05T12:40:00Z',
  },
  {
    id: 'CUST-1018',
    name: 'Swati Sethi',
    email: 'swati.s@example.com',
    phone: '+91 98188 44321',
    tier: 'platinum',
    riskScore: 7,
    trustScore: 93,
    totalOrders: 47,
    totalSpent: 108500,
    lifetimeRefunds: 1,
    status: 'active',
    createdAt: '2023-01-25T10:50:00Z',
  },
  {
    id: 'CUST-1019',
    name: 'Nikhil Rane',
    email: 'nikhil.r@example.com',
    phone: '+91 98219 77610',
    tier: 'standard',
    riskScore: 68,
    trustScore: 45,
    totalOrders: 5,
    totalSpent: 39000,
    lifetimeRefunds: 1,
    status: 'flagged',
    createdAt: '2024-01-18T15:30:00Z',
  },
  {
    id: 'CUST-1020',
    name: 'Aishwarya Rao',
    email: 'aishwarya.rao@example.com',
    phone: '+91 97411 33209',
    tier: 'gold',
    riskScore: 10,
    trustScore: 90,
    totalOrders: 33,
    totalSpent: 73400,
    lifetimeRefunds: 0,
    status: 'active',
    createdAt: '2023-05-08T11:20:00Z',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-8842',
    orderNumber: 'ORD8842',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    product: 'UltraBass Noise-Cancelling Headphones',
    amount: 2499,
    status: 'DELAYED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 2499,
    trackingId: 'TRK-BLUEDART-882190',
    courier: 'BlueDart Air',
    estimatedDelivery: '2026-09-12T18:00:00Z',
    daysDelayed: 6,
    createdAt: '2026-09-08T09:20:00Z',
  },
  {
    id: 'ORD-9103',
    orderNumber: 'ORD9103',
    customerId: 'CUST-1002',
    customerName: 'Priya Patel',
    product: 'SmartFit Gen-4 Fitness Tracker',
    amount: 3299,
    status: 'DAMAGED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 3299,
    trackingId: 'TRK-DELHIVERY-491022',
    courier: 'Delhivery Surface',
    estimatedDelivery: '2026-09-16T15:00:00Z',
    actualDelivery: '2026-09-16T14:10:00Z',
    daysDelayed: 0,
    createdAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'ORD-7721',
    orderNumber: 'ORD7721',
    customerId: 'CUST-1003',
    customerName: 'Vikram Singhania',
    product: 'Titan Apex RTX 4080 Gaming Rig',
    amount: 50000,
    status: 'IN_TRANSIT',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 50000,
    trackingId: 'TRK-EKART-772109',
    courier: 'Ekart Logistics',
    estimatedDelivery: '2026-09-20T20:00:00Z',
    daysDelayed: 0,
    createdAt: '2026-09-17T02:14:00Z',
  },
  {
    id: 'ORD-6610',
    orderNumber: 'ORD6610',
    customerId: 'CUST-1004',
    customerName: 'Ananya Deshmukh',
    product: 'Ergonomic Executive Mesh Chair',
    amount: 8999,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-BLUEDART-661044',
    courier: 'BlueDart Express',
    estimatedDelivery: '2026-09-10T14:00:00Z',
    actualDelivery: '2026-09-10T13:45:00Z',
    createdAt: '2026-09-07T10:00:00Z',
  },
  {
    id: 'ORD-5520',
    orderNumber: 'ORD5520',
    customerId: 'CUST-1005',
    customerName: 'Rohan Mehra',
    product: 'Mechanical RGB Gaming Keyboard',
    amount: 4199,
    status: 'DELAYED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 4199,
    trackingId: 'TRK-SHADOWFAX-552011',
    courier: 'Shadowfax',
    estimatedDelivery: '2026-09-13T18:00:00Z',
    daysDelayed: 5,
    createdAt: '2026-09-09T14:30:00Z',
  },
  {
    id: 'ORD-4430',
    orderNumber: 'ORD4430',
    customerId: 'CUST-1006',
    customerName: 'Sneha Verma',
    product: '4K Ultra-HD Monitor 27"',
    amount: 18999,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-DELHIVERY-443088',
    courier: 'Delhivery Surface',
    estimatedDelivery: '2026-09-12T16:00:00Z',
    actualDelivery: '2026-09-12T15:20:00Z',
    createdAt: '2026-09-08T16:15:00Z',
  },
  {
    id: 'ORD-3340',
    orderNumber: 'ORD3340',
    customerId: 'CUST-1007',
    customerName: 'Karan Kapoor',
    product: 'Wireless Qi Charging Dock Pro',
    amount: 1799,
    status: 'DELAYED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 1799,
    trackingId: 'TRK-XPRESSBEES-334099',
    courier: 'Xpressbees',
    estimatedDelivery: '2026-09-14T19:00:00Z',
    daysDelayed: 4,
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'ORD-2250',
    orderNumber: 'ORD2250',
    customerId: 'CUST-1008',
    customerName: 'Neha Roy',
    product: 'Ceramic Pour-Over Coffee Maker',
    amount: 1499,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 1499,
    trackingId: 'TRK-BLUEDART-225077',
    courier: 'BlueDart Air',
    estimatedDelivery: '2026-09-15T13:00:00Z',
    actualDelivery: '2026-09-15T12:30:00Z',
    createdAt: '2026-09-12T10:45:00Z',
  },
  {
    id: 'ORD-1160',
    orderNumber: 'ORD1160',
    customerId: 'CUST-1009',
    customerName: 'Aditya Kulkarni',
    product: 'Compact PowerBank 20000mAh',
    amount: 1999,
    status: 'DELAYED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 1999,
    trackingId: 'TRK-EKART-116033',
    courier: 'Ekart Logistics',
    estimatedDelivery: '2026-09-13T17:00:00Z',
    daysDelayed: 5,
    createdAt: '2026-09-09T08:30:00Z',
  },
  {
    id: 'ORD-9970',
    orderNumber: 'ORD9970',
    customerId: 'CUST-1010',
    customerName: 'Meera Nambiar',
    product: 'Noise-Cancelling Earbuds TWS',
    amount: 3499,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-DELHIVERY-997012',
    courier: 'Delhivery Surface',
    estimatedDelivery: '2026-09-11T16:00:00Z',
    actualDelivery: '2026-09-11T14:50:00Z',
    createdAt: '2026-09-07T11:20:00Z',
  },
  {
    id: 'ORD-8880',
    orderNumber: 'ORD8880',
    customerId: 'CUST-1011',
    customerName: 'Deepak Joshi',
    product: 'Dual Band WiFi 6 Mesh Router',
    amount: 6999,
    status: 'IN_TRANSIT',
    paymentStatus: 'DISPUTED',
    refundEligible: false,
    refundAmount: 6999,
    trackingId: 'TRK-SHADOWFAX-888055',
    courier: 'Shadowfax',
    estimatedDelivery: '2026-09-19T18:00:00Z',
    daysDelayed: 0,
    createdAt: '2026-09-16T18:40:00Z',
  },
  {
    id: 'ORD-7790',
    orderNumber: 'ORD7790',
    customerId: 'CUST-1012',
    customerName: 'Kavita Sundaram',
    product: 'HydroFlask Thermal Tumbler 1L',
    amount: 1850,
    status: 'DAMAGED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 1850,
    trackingId: 'TRK-BLUEDART-779021',
    courier: 'BlueDart Air',
    estimatedDelivery: '2026-09-16T14:00:00Z',
    actualDelivery: '2026-09-16T13:10:00Z',
    daysDelayed: 0,
    createdAt: '2026-09-13T09:10:00Z',
  },
  {
    id: 'ORD-6601',
    orderNumber: 'ORD6601',
    customerId: 'CUST-1013',
    customerName: 'Tanmay Ghosh',
    product: 'Studio Condenser Mic Kit',
    amount: 3899,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-EKART-660189',
    courier: 'Ekart Logistics',
    estimatedDelivery: '2026-09-14T15:00:00Z',
    actualDelivery: '2026-09-14T14:40:00Z',
    createdAt: '2026-09-10T15:25:00Z',
  },
  {
    id: 'ORD-5512',
    orderNumber: 'ORD5512',
    customerId: 'CUST-1014',
    customerName: 'Ritu Choudhury',
    product: 'Smart LED Desk Lamp w/ Wireless Qi',
    amount: 2299,
    status: 'DELAYED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 2299,
    trackingId: 'TRK-DELHIVERY-551230',
    courier: 'Delhivery Surface',
    estimatedDelivery: '2026-09-14T18:00:00Z',
    daysDelayed: 4,
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'ORD-4423',
    orderNumber: 'ORD4423',
    customerId: 'CUST-1015',
    customerName: 'Arjun Bansal',
    product: 'Enterprise Barcode Scanner Bluetooth',
    amount: 12499,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-BLUEDART-442391',
    courier: 'BlueDart Express',
    estimatedDelivery: '2026-09-11T12:00:00Z',
    actualDelivery: '2026-09-11T11:20:00Z',
    createdAt: '2026-09-08T13:40:00Z',
  },
  {
    id: 'ORD-3334',
    orderNumber: 'ORD3334',
    customerId: 'CUST-1016',
    customerName: 'Pooja Hegde',
    product: 'Aromatherapy Ultrasonic Diffuser',
    amount: 1199,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 1199,
    trackingId: 'TRK-XPRESSBEES-333412',
    courier: 'Xpressbees',
    estimatedDelivery: '2026-09-15T17:00:00Z',
    actualDelivery: '2026-09-15T16:15:00Z',
    createdAt: '2026-09-12T14:10:00Z',
  },
  {
    id: 'ORD-2245',
    orderNumber: 'ORD2245',
    customerId: 'CUST-1017',
    customerName: 'Manish Tiwari',
    product: 'Aluminum Vertical Laptop Stand',
    amount: 1650,
    status: 'DELAYED',
    paymentStatus: 'PAID',
    refundEligible: true,
    refundAmount: 1650,
    trackingId: 'TRK-SHADOWFAX-224580',
    courier: 'Shadowfax',
    estimatedDelivery: '2026-09-13T19:00:00Z',
    daysDelayed: 5,
    createdAt: '2026-09-09T17:00:00Z',
  },
  {
    id: 'ORD-1156',
    orderNumber: 'ORD1156',
    customerId: 'CUST-1018',
    customerName: 'Swati Sethi',
    product: 'Smart Water Bottle Hydration Reminder',
    amount: 2799,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-DELHIVERY-115699',
    courier: 'Delhivery Surface',
    estimatedDelivery: '2026-09-12T15:00:00Z',
    actualDelivery: '2026-09-12T14:00:00Z',
    createdAt: '2026-09-08T11:45:00Z',
  },
  {
    id: 'ORD-9967',
    orderNumber: 'ORD9967',
    customerId: 'CUST-1019',
    customerName: 'Nikhil Rane',
    product: 'Flagship Smartphone Pro 256GB',
    amount: 64999,
    status: 'IN_TRANSIT',
    paymentStatus: 'DISPUTED',
    refundEligible: false,
    refundAmount: 64999,
    trackingId: 'TRK-BLUEDART-996740',
    courier: 'BlueDart Express',
    estimatedDelivery: '2026-09-21T18:00:00Z',
    daysDelayed: 0,
    createdAt: '2026-09-17T08:10:00Z',
  },
  {
    id: 'ORD-8878',
    orderNumber: 'ORD8878',
    customerId: 'CUST-1020',
    customerName: 'Aishwarya Rao',
    product: 'Handheld Garment Steamer 1200W',
    amount: 2199,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-EKART-887823',
    courier: 'Ekart Logistics',
    estimatedDelivery: '2026-09-14T16:00:00Z',
    actualDelivery: '2026-09-14T15:30:00Z',
    createdAt: '2026-09-11T12:50:00Z',
  },
  {
    id: 'ORD-7789',
    orderNumber: 'ORD7789',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    product: 'Ultra-Slim Wireless Mouse',
    amount: 899,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-BLUEDART-778911',
    courier: 'BlueDart Air',
    estimatedDelivery: '2026-08-20T14:00:00Z',
    actualDelivery: '2026-08-20T13:40:00Z',
    createdAt: '2026-08-17T10:00:00Z',
  },
  {
    id: 'ORD-6691',
    orderNumber: 'ORD6691',
    customerId: 'CUST-1002',
    customerName: 'Priya Patel',
    product: 'Silicone Sport Band for Watch',
    amount: 599,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-DELHIVERY-669123',
    courier: 'Delhivery Surface',
    estimatedDelivery: '2026-07-15T16:00:00Z',
    actualDelivery: '2026-07-15T15:10:00Z',
    createdAt: '2026-07-12T11:00:00Z',
  },
  {
    id: 'ORD-5503',
    orderNumber: 'ORD5503',
    customerId: 'CUST-1004',
    customerName: 'Ananya Deshmukh',
    product: 'Under-Desk Cable Management Tray',
    amount: 1299,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-EKART-550344',
    courier: 'Ekart Logistics',
    estimatedDelivery: '2026-08-05T14:00:00Z',
    actualDelivery: '2026-08-05T13:20:00Z',
    createdAt: '2026-08-02T16:00:00Z',
  },
  {
    id: 'ORD-4415',
    orderNumber: 'ORD4415',
    customerId: 'CUST-1005',
    customerName: 'Rohan Mehra',
    product: 'PBT Keycaps Double-Shot Set',
    amount: 1899,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-SHADOWFAX-441512',
    courier: 'Shadowfax',
    estimatedDelivery: '2026-07-28T18:00:00Z',
    actualDelivery: '2026-07-28T17:00:00Z',
    createdAt: '2026-07-25T14:00:00Z',
  },
  {
    id: 'ORD-3326',
    orderNumber: 'ORD3326',
    customerId: 'CUST-1006',
    customerName: 'Sneha Verma',
    product: 'Screen LightBar USB Powered',
    amount: 2999,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-BLUEDART-332678',
    courier: 'BlueDart Air',
    estimatedDelivery: '2026-08-11T12:00:00Z',
    actualDelivery: '2026-08-11T11:45:00Z',
    createdAt: '2026-08-08T09:00:00Z',
  },
  {
    id: 'ORD-2237',
    orderNumber: 'ORD2237',
    customerId: 'CUST-1008',
    customerName: 'Neha Roy',
    product: 'Electric Gooseneck Kettle 800ml',
    amount: 3499,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-DELHIVERY-223790',
    courier: 'Delhivery Surface',
    estimatedDelivery: '2026-06-18T16:00:00Z',
    actualDelivery: '2026-06-18T15:20:00Z',
    createdAt: '2026-06-15T10:15:00Z',
  },
  {
    id: 'ORD-1148',
    orderNumber: 'ORD1148',
    customerId: 'CUST-1010',
    customerName: 'Meera Nambiar',
    product: 'Braided Fast Charging Cable 2M',
    amount: 499,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-XPRESSBEES-114822',
    courier: 'Xpressbees',
    estimatedDelivery: '2026-07-09T14:00:00Z',
    actualDelivery: '2026-07-09T13:50:00Z',
    createdAt: '2026-07-06T12:00:00Z',
  },
  {
    id: 'ORD-9959',
    orderNumber: 'ORD9959',
    customerId: 'CUST-1012',
    customerName: 'Kavita Sundaram',
    product: 'Stainless Steel Insulated Straw Lid',
    amount: 350,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-EKART-995901',
    courier: 'Ekart Logistics',
    estimatedDelivery: '2026-08-25T15:00:00Z',
    actualDelivery: '2026-08-25T14:15:00Z',
    createdAt: '2026-08-22T08:30:00Z',
  },
  {
    id: 'ORD-8861',
    orderNumber: 'ORD8861',
    customerId: 'CUST-1015',
    customerName: 'Arjun Bansal',
    product: 'Thermal Receipt Paper Rolls (Pack of 20)',
    amount: 999,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-BLUEDART-886134',
    courier: 'BlueDart Express',
    estimatedDelivery: '2026-08-14T11:00:00Z',
    actualDelivery: '2026-08-14T10:40:00Z',
    createdAt: '2026-08-11T16:20:00Z',
  },
  {
    id: 'ORD-7772',
    orderNumber: 'ORD7772',
    customerId: 'CUST-1018',
    customerName: 'Swati Sethi',
    product: 'Fruit Infuser Water Filter Cap',
    amount: 450,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    refundEligible: false,
    refundAmount: 0,
    trackingId: 'TRK-SHADOWFAX-777265',
    courier: 'Shadowfax',
    estimatedDelivery: '2026-07-22T17:00:00Z',
    actualDelivery: '2026-07-22T16:00:00Z',
    createdAt: '2026-07-19T13:10:00Z',
  },
];

export const MOCK_CASES: Case[] = [
  {
    id: 'CASE-1024',
    ticketNumber: 'REQ-1024',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    customerTier: 'platinum',
    intent: 'Delayed Order & Refund Request',
    orderNumber: 'ORD8842',
    productName: 'UltraBass Noise-Cancelling Headphones',
    amount: 2499,
    currency: 'INR',
    priority: 'MEDIUM',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'REFUND_DISPATCHED',
    verificationStatus: 'VERIFIED',
    verificationDetails: {
      verifiedAt: '2026-09-18T14:31:11Z',
      gatewayRefId: 'REF-PAYTM-99214',
      checkName: 'Payment Gateway Ledger Settlement Confirmation',
      confirmed: true,
    },
    resolution:
      'Autonomous refund of ₹2,499 authorized and verified. Settlement reference REF-PAYTM-99214 confirmed by banking gateway. Notification dispatched via WhatsApp and SMS.',
    customerMessage: "My order hasn't arrived and I want a refund.",
    aiResponse:
      'We verified your order ORD8842 is delayed by 6 days past SLA. A full refund of ₹2,499 has been credited back to your original payment method (Ref: REF-PAYTM-99214).',
    refundId: 'REF-PAYTM-99214',
    createdAt: '2026-09-18T14:31:04Z',
    updatedAt: '2026-09-18T14:31:12Z',
    timeline: [
      {
        id: 'ev-1',
        timestamp: '14:31:04',
        type: 'REQUEST_RECEIVED',
        title: 'Customer Request Received',
        description: 'Inbound message processed via digital intake endpoint',
        status: 'success',
      },
      {
        id: 'ev-2',
        timestamp: '14:31:05',
        type: 'INTENT_IDENTIFIED',
        title: 'Intent & Entity Extraction',
        description: 'Identified primary intent: refund_request | target entity: ORD8842',
        status: 'success',
        tool: 'CRM',
      },
      {
        id: 'ev-3',
        timestamp: '14:31:06',
        type: 'CUSTOMER_VERIFIED',
        title: 'Customer Verified',
        description: 'Matched CUST-1001 (Platinum tier, trust score 94/100)',
        status: 'success',
        tool: 'CRM',
      },
      {
        id: 'ev-4',
        timestamp: '14:31:07',
        type: 'ORDER_RETRIEVED',
        title: 'Logistics Telemetry Retrieved',
        description: 'Tracking TRK-BLUEDART-882190 indicates 6 days delay past SLA',
        status: 'warning',
        tool: 'ORDERS',
      },
      {
        id: 'ev-5',
        timestamp: '14:31:08',
        type: 'POLICY_EVALUATED',
        title: 'Deterministic Policy Evaluation',
        description: 'Rule POL-402 matched: Delivery delay > 48h qualifies for 100% refund',
        status: 'success',
      },
      {
        id: 'ev-6',
        timestamp: '14:31:09',
        type: 'ACTION_AUTHORIZED',
        title: 'Autonomous Action Authorized',
        description: 'Amount ₹2,499 is within autonomous limit ₹5,000. Risk level LOW.',
        status: 'success',
      },
      {
        id: 'ev-7',
        timestamp: '14:31:10',
        type: 'ACTION_EXECUTED',
        title: 'Refund Payout Dispatched',
        description: 'Dispatched payout instruction to Paytm Payment Gateway',
        status: 'active',
        tool: 'REFUNDS',
      },
      {
        id: 'ev-8',
        timestamp: '14:31:11',
        type: 'RESULT_VERIFIED',
        title: 'Gateway Reconciliation Verified',
        description: 'Gateway receipt REF-PAYTM-99214 reconciled with bank ledger',
        status: 'success',
        tool: 'PAYMENTS',
      },
      {
        id: 'ev-9',
        timestamp: '14:31:12',
        type: 'CUSTOMER_NOTIFIED',
        title: 'Customer Comms Sent',
        description: 'Multi-channel notification dispatched via WhatsApp and SMS',
        status: 'success',
        tool: 'NOTIFICATIONS',
      },
      {
        id: 'ev-10',
        timestamp: '14:31:12',
        type: 'CASE_RESOLVED',
        title: 'Case Closed Autonomously',
        description: 'Audit record synchronized to core ticket registry',
        status: 'success',
        tool: 'TICKETS',
      },
    ],
  },
  {
    id: 'CASE-1025',
    ticketNumber: 'REQ-1025',
    customerId: 'CUST-1002',
    customerName: 'Priya Patel',
    customerTier: 'gold',
    intent: 'Damaged Item Replacement',
    orderNumber: 'ORD9103',
    productName: 'SmartFit Gen-4 Fitness Tracker',
    amount: 3299,
    currency: 'INR',
    priority: 'MEDIUM',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'REPLACEMENT_ORDER_CREATED',
    verificationStatus: 'VERIFIED',
    verificationDetails: {
      verifiedAt: '2026-09-18T11:15:30Z',
      gatewayRefId: 'ORD-REPL-5510',
      checkName: 'Warehouse Inventory Allocation & Dispatch Order ID',
      confirmed: true,
    },
    resolution:
      'Replacement order ORD-REPL-5510 provisioned in central warehouse. Return pickup scheduled for damaged unit on Sep 19.',
    customerMessage: 'The product I received is damaged. I want a replacement.',
    aiResponse:
      'Your replacement order ORD-REPL-5510 has been placed and will be delivered by Sep 20. Our courier will pick up the damaged unit at delivery.',
    replacementOrderId: 'ORD-REPL-5510',
    createdAt: '2026-09-18T11:15:20Z',
    updatedAt: '2026-09-18T11:15:32Z',
    timeline: [
      {
        id: 'ev-1025-1',
        timestamp: '11:15:20',
        type: 'REQUEST_RECEIVED',
        title: 'Replacement Request Received',
        description: 'Customer reported physical damage on arrival for ORD9103',
        status: 'success',
      },
      {
        id: 'ev-1025-2',
        timestamp: '11:15:22',
        type: 'INTENT_IDENTIFIED',
        title: 'Policy & Return Window Validated',
        description: 'Delivered within 48h; eligible for instant free replacement',
        status: 'success',
        tool: 'ORDERS',
      },
      {
        id: 'ev-1025-3',
        timestamp: '11:15:26',
        type: 'ACTION_EXECUTED',
        title: 'Replacement Order Provisioned',
        description: 'Created replacement SKU in fulfillment hub (ORD-REPL-5510)',
        status: 'active',
        tool: 'ORDERS',
      },
      {
        id: 'ev-1025-4',
        timestamp: '11:15:30',
        type: 'RESULT_VERIFIED',
        title: 'Warehouse Allocation Verified',
        description: 'Inventory reserved at Mumbai Hub. Return docket generated.',
        status: 'success',
        tool: 'TICKETS',
      },
      {
        id: 'ev-1025-5',
        timestamp: '11:15:32',
        type: 'CASE_RESOLVED',
        title: 'Replacement Confirmed',
        description: 'Customer notification sent with return label and tracking link',
        status: 'success',
        tool: 'NOTIFICATIONS',
      },
    ],
  },
  {
    id: 'CASE-1026',
    ticketNumber: 'REQ-1026',
    customerId: 'CUST-1003',
    customerName: 'Vikram Singhania',
    customerTier: 'standard',
    intent: 'Unauthorized Transaction Dispute',
    orderNumber: 'ORD7721',
    productName: 'Titan Apex RTX 4080 Gaming Rig',
    amount: 50000,
    currency: 'INR',
    priority: 'CRITICAL',
    risk: 'HIGH',
    status: 'ESCALATED',
    decision: 'HUMAN_REVIEW',
    currentAction: 'SUPERVISOR_TRIAGE_PENDING',
    verificationStatus: 'SKIPPED',
    resolution:
      'High transaction value (₹50,000) exceeds autonomous boundary (₹5,000). High risk score (82/100) and device geolocation variance detected. Escalated to Security Supervisor.',
    customerMessage: 'I think someone made an unauthorized ₹50,000 transaction.',
    aiResponse:
      'We have flagged transaction ORD7721 (₹50,000) for high-priority security review. A Senior Risk Officer is investigating and will reach you within 15 minutes.',
    createdAt: '2026-09-18T13:45:00Z',
    updatedAt: '2026-09-18T13:45:15Z',
    timeline: [
      {
        id: 'ev-1026-1',
        timestamp: '13:45:00',
        type: 'REQUEST_RECEIVED',
        title: 'Dispute Claim Lodged',
        description: 'Customer reported unauthorized charge of ₹50,000',
        status: 'warning',
      },
      {
        id: 'ev-1026-2',
        timestamp: '13:45:03',
        type: 'CUSTOMER_VERIFIED',
        title: 'Customer Profile Assessed',
        description: 'Customer trust score 31/100; flagged for previous return fraud alerts',
        status: 'warning',
        tool: 'CRM',
      },
      {
        id: 'ev-1026-3',
        timestamp: '13:45:06',
        type: 'RISK_ASSESSED',
        title: 'Risk Engine Scored 82/100',
        description: 'Transaction exceeds ₹5,000 limit + device IP mismatch detected',
        status: 'error',
      },
      {
        id: 'ev-1026-4',
        timestamp: '13:45:10',
        type: 'ESCALATED',
        title: 'Autonomous Execution Halted',
        description: 'Policy forbids autonomous refund on high-value fraud alerts',
        status: 'error',
        tool: 'HUMAN',
      },
      {
        id: 'ev-1026-5',
        timestamp: '13:45:15',
        type: 'ESCALATED',
        title: 'Transferred to Human Escalation Center',
        description: 'Comprehensive investigation brief generated for Risk Specialist',
        status: 'warning',
        tool: 'HUMAN',
      },
    ],
  },
  {
    id: 'CASE-1027',
    ticketNumber: 'REQ-1027',
    customerId: 'CUST-1005',
    customerName: 'Rohan Mehra',
    customerTier: 'gold',
    intent: 'Delivery Delay Inquiry',
    orderNumber: 'ORD5520',
    productName: 'Mechanical RGB Gaming Keyboard',
    amount: 4199,
    currency: 'INR',
    priority: 'MEDIUM',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'EXPEDITED_DISPATCH_PING',
    verificationStatus: 'VERIFIED',
    verificationDetails: {
      verifiedAt: '2026-09-17T16:20:10Z',
      gatewayRefId: 'SHDW-PRIORITY-991',
      checkName: 'Courier Priority Hub Escalation ACK',
      confirmed: true,
    },
    resolution:
      'Courier hub bottleneck cleared. Priority re-dispatch confirmed with delivery scheduled today.',
    customerMessage: 'Where is my order? It has been 5 days.',
    aiResponse:
      'We contacted Shadowfax dispatch hub. Your shipment is out for delivery today and you have received ₹150 courtesy wallet credit.',
    createdAt: '2026-09-17T16:20:00Z',
    updatedAt: '2026-09-17T16:20:12Z',
    timeline: [],
  },
  {
    id: 'CASE-1028',
    ticketNumber: 'REQ-1028',
    customerId: 'CUST-1007',
    customerName: 'Karan Kapoor',
    customerTier: 'standard',
    intent: 'Refund Request',
    orderNumber: 'ORD3340',
    productName: 'Wireless Qi Charging Dock Pro',
    amount: 1799,
    currency: 'INR',
    priority: 'LOW',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'REFUND_DISPATCHED',
    verificationStatus: 'VERIFIED',
    refundId: 'REF-PAYTM-44120',
    createdAt: '2026-09-17T12:10:00Z',
    updatedAt: '2026-09-17T12:10:14Z',
    timeline: [],
  },
  {
    id: 'CASE-1029',
    ticketNumber: 'REQ-1029',
    customerId: 'CUST-1011',
    customerName: 'Deepak Joshi',
    customerTier: 'standard',
    intent: 'Payment Dispute',
    orderNumber: 'ORD8880',
    productName: 'Dual Band WiFi 6 Mesh Router',
    amount: 6999,
    currency: 'INR',
    priority: 'HIGH',
    risk: 'HIGH',
    status: 'ESCALATED',
    decision: 'HUMAN_REVIEW',
    currentAction: 'SUPERVISOR_TRIAGE_PENDING',
    verificationStatus: 'SKIPPED',
    resolution: 'Amount ₹6,999 exceeds auto threshold. Customer flagged for risk.',
    createdAt: '2026-09-17T10:05:00Z',
    updatedAt: '2026-09-17T10:05:12Z',
    timeline: [],
  },
  {
    id: 'CASE-1030',
    ticketNumber: 'REQ-1030',
    customerId: 'CUST-1012',
    customerName: 'Kavita Sundaram',
    customerTier: 'gold',
    intent: 'Damaged Lid Replacement',
    orderNumber: 'ORD7790',
    productName: 'HydroFlask Thermal Tumbler 1L',
    amount: 1850,
    currency: 'INR',
    priority: 'LOW',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'REPLACEMENT_ORDER_CREATED',
    verificationStatus: 'VERIFIED',
    replacementOrderId: 'ORD-REPL-6621',
    createdAt: '2026-09-16T15:40:00Z',
    updatedAt: '2026-09-16T15:40:11Z',
    timeline: [],
  },
  {
    id: 'CASE-1031',
    ticketNumber: 'REQ-1031',
    customerId: 'CUST-1014',
    customerName: 'Ritu Choudhury',
    customerTier: 'gold',
    intent: 'Refund on Delayed Lamp',
    orderNumber: 'ORD5512',
    productName: 'Smart LED Desk Lamp w/ Wireless Qi',
    amount: 2299,
    currency: 'INR',
    priority: 'MEDIUM',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'REFUND_DISPATCHED',
    verificationStatus: 'VERIFIED',
    refundId: 'REF-PAYTM-88210',
    createdAt: '2026-09-16T11:20:00Z',
    updatedAt: '2026-09-16T11:20:15Z',
    timeline: [],
  },
  {
    id: 'CASE-1032',
    ticketNumber: 'REQ-1032',
    customerId: 'CUST-1017',
    customerName: 'Manish Tiwari',
    customerTier: 'gold',
    productName: 'Aluminum Vertical Laptop Stand',
    amount: 1650,
    currency: 'INR',
    intent: 'Delayed Package Refund',
    orderNumber: 'ORD2245',
    priority: 'LOW',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'REFUND_DISPATCHED',
    verificationStatus: 'VERIFIED',
    refundId: 'REF-PAYTM-11239',
    createdAt: '2026-09-15T18:00:00Z',
    updatedAt: '2026-09-15T18:00:10Z',
    timeline: [],
  },
  {
    id: 'CASE-1033',
    ticketNumber: 'REQ-1033',
    customerId: 'CUST-1019',
    customerName: 'Nikhil Rane',
    customerTier: 'standard',
    intent: 'Chargeback / Unrecognized Order',
    orderNumber: 'ORD9967',
    productName: 'Flagship Smartphone Pro 256GB',
    amount: 64999,
    currency: 'INR',
    priority: 'CRITICAL',
    risk: 'HIGH',
    status: 'ESCALATED',
    decision: 'HUMAN_REVIEW',
    currentAction: 'INVESTIGATION_HOLD',
    verificationStatus: 'SKIPPED',
    resolution:
      'High-value electronics purchase (₹64,999) under dispute with simultaneous credit card chargeback attempt. Handed to Fraud Mitigation Squad.',
    createdAt: '2026-09-15T09:30:00Z',
    updatedAt: '2026-09-15T09:30:15Z',
    timeline: [],
  },
  {
    id: 'CASE-1034',
    ticketNumber: 'REQ-1034',
    customerId: 'CUST-1009',
    customerName: 'Aditya Kulkarni',
    customerTier: 'standard',
    intent: 'Refund on PowerBank',
    orderNumber: 'ORD1160',
    productName: 'Compact PowerBank 20000mAh',
    amount: 1999,
    currency: 'INR',
    priority: 'LOW',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'REFUND_DISPATCHED',
    verificationStatus: 'VERIFIED',
    refundId: 'REF-PAYTM-67123',
    createdAt: '2026-09-14T14:15:00Z',
    updatedAt: '2026-09-14T14:15:10Z',
    timeline: [],
  },
  {
    id: 'CASE-1035',
    ticketNumber: 'REQ-1035',
    customerId: 'CUST-1016',
    customerName: 'Pooja Hegde',
    customerTier: 'standard',
    intent: 'Missing Aroma Diffuser Oil Bottle',
    orderNumber: 'ORD3334',
    productName: 'Aromatherapy Ultrasonic Diffuser',
    amount: 1199,
    currency: 'INR',
    priority: 'LOW',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'PARTIAL_REFUND_WALLET',
    verificationStatus: 'VERIFIED',
    refundId: 'REF-WALLET-4410',
    createdAt: '2026-09-14T11:00:00Z',
    updatedAt: '2026-09-14T11:00:12Z',
    timeline: [],
  },
  {
    id: 'CASE-1036',
    ticketNumber: 'REQ-1036',
    customerId: 'CUST-1006',
    customerName: 'Sneha Verma',
    customerTier: 'platinum',
    intent: 'Screen LightBar Firmware Inquiry',
    orderNumber: 'ORD3326',
    productName: 'Screen LightBar USB Powered',
    amount: 2999,
    currency: 'INR',
    priority: 'LOW',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'DOCUMENTATION_DISPATCH',
    verificationStatus: 'VERIFIED',
    createdAt: '2026-09-13T16:20:00Z',
    updatedAt: '2026-09-13T16:20:08Z',
    timeline: [],
  },
  {
    id: 'CASE-1037',
    ticketNumber: 'REQ-1037',
    customerId: 'CUST-1004',
    customerName: 'Ananya Deshmukh',
    customerTier: 'enterprise',
    intent: 'Bulk VAT Invoice Correction',
    orderNumber: 'ORD6610',
    productName: 'Ergonomic Executive Mesh Chair',
    amount: 8999,
    currency: 'INR',
    priority: 'MEDIUM',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'ERP_GST_REISSUED',
    verificationStatus: 'VERIFIED',
    createdAt: '2026-09-12T13:40:00Z',
    updatedAt: '2026-09-12T13:40:15Z',
    timeline: [],
  },
  {
    id: 'CASE-1038',
    ticketNumber: 'REQ-1038',
    customerId: 'CUST-1008',
    customerName: 'Neha Roy',
    customerTier: 'gold',
    intent: 'Kettle Temperature Calibration',
    orderNumber: 'ORD2237',
    productName: 'Electric Gooseneck Kettle 800ml',
    amount: 3499,
    currency: 'INR',
    priority: 'LOW',
    risk: 'LOW',
    status: 'RESOLVED',
    decision: 'AUTO_RESOLVE',
    currentAction: 'TECH_GUIDE_DISPATCH',
    verificationStatus: 'VERIFIED',
    createdAt: '2026-09-11T15:10:00Z',
    updatedAt: '2026-09-11T15:10:09Z',
    timeline: [],
  },
];

export const MOCK_ESCALATIONS: Escalation[] = [
  {
    id: 'ESC-001',
    ticketId: 'CASE-1026',
    caseNumber: 'REQ-1026',
    customerId: 'CUST-1003',
    customerName: 'Vikram Singhania',
    issue: 'High-value transaction dispute (₹50,000 Gaming Rig)',
    priority: 'CRITICAL',
    riskLevel: 'HIGH',
    amount: 50000,
    aiSummary:
      'Customer claims unauthorized purchase of RTX 4080 Gaming Rig. Order amount (₹50,000) exceeds maximum autonomous refund authorization threshold (₹5,000). High risk profile (Score: 82/100) with suspicious IP geofence variance (Mumbai card used from Bucharest IP proxy).',
    actionsAttempted: [
      'Customer identity verified in CRM',
      'Order status checked with Ekart Logistics',
      'Transaction payment ledger analyzed',
      'Deterministic policy engine triggered limit guardrail',
    ],
    reason:
      'Autonomous policy limit exceeded (₹50,000 > ₹5,000) and elevated fraud risk probability (82/100).',
    recommendedAction:
      'Hold shipment with courier dispatch hub immediately, initiate two-factor phone callback to customer, and verify credit card issuing bank authorization.',
    status: 'PENDING_REVIEW',
    createdAt: '2026-09-18T13:45:15Z',
  },
  {
    id: 'ESC-002',
    ticketId: 'CASE-1029',
    caseNumber: 'REQ-1029',
    customerId: 'CUST-1011',
    customerName: 'Deepak Joshi',
    issue: 'Mesh Router payment disputed with bank gateway',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    amount: 6999,
    aiSummary:
      'Customer dispute on WiFi Router (₹6,999). Amount is above ₹5,000 limit. Customer previously filed 2 refund requests within 30 days. Risk score 75/100.',
    actionsAttempted: [
      'Customer profile reviewed',
      '30-day dispute history cross-checked',
      'Bank gateway authorization log queried',
    ],
    reason: 'Frequent dispute pattern detected + transaction value above auto threshold.',
    recommendedAction:
      'Review previous return photographic records and confirm serial number delivery receipt with Shadowfax.',
    status: 'ASSIGNED',
    assignedTo: 'Anil Mehta (Senior Risk Analyst)',
    createdAt: '2026-09-17T10:05:12Z',
  },
  {
    id: 'ESC-003',
    ticketId: 'CASE-1033',
    caseNumber: 'REQ-1033',
    customerId: 'CUST-1019',
    customerName: 'Nikhil Rane',
    issue: 'Potential credit card fraud chargeback (₹64,999)',
    priority: 'CRITICAL',
    riskLevel: 'HIGH',
    amount: 64999,
    aiSummary:
      'Customer filed fraud report for Flagship Smartphone purchase. Order is currently in transit with BlueDart Express. Automatic halt on dispatch advised.',
    actionsAttempted: [
      'Order located in transit',
      'Courier telematics pinged',
      'Bank chargeback advisory matched',
    ],
    reason: 'Chargeback advisory received from Visa network with pending delivery.',
    recommendedAction:
      'Issue emergency courier recall to return unit to central warehouse and prevent inventory loss.',
    status: 'ACKNOWLEDGED',
    assignedTo: 'Sunita Rao (Fraud Operations Lead)',
    createdAt: '2026-09-15T09:30:15Z',
  },
];
